services:
  redis:
    image: redis:latest
    container_name: redis-job-queue
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--notify-keyspace-events", "Ex"]

volumes:
  redis_data:
    driver: local